### ISSUE TITLE
readthedocs documentation

### ISSUE THREAD

**Issue by scarrazza** [qiboteam/qibocal#100]
In order to generate documentation for readthedocs, qibolab must be public, I had just setup the building process but it crashes due to access to qibolab code repo.

On the other hand, I believe at some point qibolab could be a simple dependency.
@andrea-pasquale and @stavros11 any thoughts?

**Comment by andrea-pasquale** [comment]
I had a similar issue when try to use `dependabot` to update some deps.
As soon as we make qibolab public everything should be easier.

**Comment by andrea-pasquale** [comment]
@scarrazza since now qibolab is public could you please generate the documentation for readthedocs?

**Comment by scarrazza** [comment]
@andrea-pasquale, I believe we are missing some dependencies, see [this build](https://readthedocs.org/projects/qibocal/builds/18502569/).

**Comment by andrea-pasquale** [comment]
Yes, this is happening because we have updated the deps in qibolab. 
I've already a PR in order to fix this (#135). I believe that if we merge it to main also readthedocs should compile without issues.
The PR should be ready to merge to main.

**Comment by scarrazza** [comment]
We are close: https://readthedocs.org/projects/qibocal/builds/18505459/

**Comment by andrea-pasquale** [comment]
This is strange...
I'll have a look.

**Comment by andrea-pasquale** [comment]
There was a typo the correct module is `sphinx_markdown_tables` and not `sphinx-markdown-tables`.
I've pushed to main the pyproject.toml with the correct module.

**Comment by scarrazza** [comment]
Not yet: https://readthedocs.org/projects/qibocal/builds/18506595/

**Comment by andrea-pasquale** [comment]
> Not yet: https://readthedocs.org/projects/qibocal/builds/18506595/

@scarrazza can I have access to this page to debug?

**Comment by scarrazza** [comment]
In principle all builds are publicly visible: https://readthedocs.org/projects/qibocal/builds/
The build starts when you commit to main.

**Comment by andrea-pasquale** [comment]
I see, I thought that you can trigger manually when to compile the documentation, my bad.

**Comment by scarrazza** [comment]
Register to the website and send me your email username by email, I can try to link so you can trigger manually.

**Comment by andrea-pasquale** [comment]
Readthedocs is finally working.
I'll close this issue.
