### ISSUE TITLE
Results from virtual_z_phases and virtual_z_phases_signal do not match

### ISSUE THREAD

**Issue by hay-k** [qiboteam/qibocal#1004]
virtual_z_phases: http://login.qrccluster.com:9000/3dRNAIU0Tgy5ebT4-7Bvog==
virtual_z_phases_signal: http://login.qrccluster.com:9000/oh4sU7f5QvapoYaqGjzoHg==/

Note that the calculated virtual phases are very different.

I believe the difference stems from the difference in these two lines:

https://github.com/qiboteam/qibocal/blob/6789ac85b096310087415369f04cad9b88eac717/src/qibocal/protocols/two_qubit_interaction/virtual_z_phases_signal.py#L102

https://github.com/qiboteam/qibocal/blob/6789ac85b096310087415369f04cad9b88eac717/src/qibocal/protocols/two_qubit_interaction/virtual_z_phases.py#L249

Changing the line in _signal to match the other one, I get matching results indeed: http://login.qrccluster.com:9000/iSWSGTFcSAKlvWGOrDFA1g==

**Comment by andrea-pasquale** [comment]
Thanks for spotting this @hay-k.
I forgot to change also the signal protocol in #972
