### ISSUE TITLE
implementation of new NZ pulse chracterization routine

### ISSUE THREAD

**Issue by DavidSarlle** [qiboteam/qibocal#1027]
https://arxiv.org/pdf/1903.02492

**Comment by Edoardo-Pedicillo** [comment]
Thanks @DavidSarlle, in our roadmap (https://github.com/qiboteam/qibocal/blob/main/doc/dev/README.md#:~:text=SNZ%20/%20Martini%20Ansatz%20(https%3A//arxiv.org/pdf/2008.07411%20https%3A//arxiv.org/pdf/1402.5467) ) we have the implementation of the SNZ pulse that should be an improvement of the NZ pulse

**Comment by DavidSarlle** [comment]
ok, perfect! Thanks @Edoardo-Pedicillo
