### ISSUE TITLE
Completing documentation

### ISSUE THREAD

**Issue by scarrazza** [qiboteam/qibocal#103]
In order to provide an useful documentation please find below my wishlist (be free to include more features):
- [x] complete installation instructions. Include CI tests for linux, mac and windows for multiple version of python. So we can tell which configurations are supported.
- [x] complete qq-upload docs
- [ ] include references to real actions names, cleanup examples, include links to examples. Add step by step instructions explaining how to run the code.
- [ ] complete all calibrations by adding proper docstrings with explanation and references and including examples. If possible include some example of plots so people are aware of what expect. Someone new to the topic should understand what each action is doing.
- [ ] add documentation about live plotting, with some examples
- [x] talk about the output data structure, show examples
- [x] update README

**Comment by scarrazza** [comment]
@andrea-pasquale concerning tests, if you want I can enable the qpu runner in this repo too. Let me know.

**Comment by andrea-pasquale** [comment]
Thanks @scarrazza that would be great.

**Comment by scarrazza** [comment]
Done.
