### ISSUE TITLE
Two qubit state tomography reporting incorrect density matrix

### ISSUE THREAD

**Issue by Edoardo-Pedicillo** [qiboteam/qibocal#1032]
In the report of this protocol, this matrix is showed

https://github.com/qiboteam/qibocal/blob/fa0467c73b7d91e23c88b944ba5e651393c3a0da/src/qibocal/protocols/two_qubit_state_tomography.py#L298-L300

After discussing with @stavros11, these lines should be replaced by
```py

 measured = np.array(fit.measured_density_matrix_real[target]) + 1j * np.array( 
     fit.measured_density_matrix_imag[target] 
 ) 

```

**Comment by alecandido** [comment]
To avoid running the diff again: the difference is that in the imaginary part the `measured_raw_density_...` is replaced by `measured_density` (maybe people are in general more careful to details than I am, but I struggled a bit finding the difference...)
