### ISSUE TITLE
Add docstrings for calibration routines

### ISSUE THREAD

**Issue by andrea-pasquale** [qiboteam/qibocal#119]
In order to write a proper documentation we need to have docstrings for all functions and methods.
In particular we need to document all the calibration routines that we have in qibocal.
@aorgazf @maxhant @DavidSarlle could you please take care of this?

You can have a look [here](https://peps.python.org/pep-0257/) on how to write docstrings.

**Comment by scarrazza** [comment]
Implemented in #134.
