### ISSUE TITLE
Tests failing on mac os

### ISSUE THREAD

**Issue by andrea-pasquale** [qiboteam/qibocal#177]
As title says

**Comment by scarrazza** [comment]
Seems to come from black:
```
  ERROR: black-22.10.0-1fixedarch-cp39-cp39-macosx_11_0_x86_64.whl is not a supported wheel on this platform.
```

**Comment by andrea-pasquale** [comment]
Thanks @scarrazza.
There is already an [issue ](https://github.com/psf/black/issues/3312)open in the black repository about this even if it is from Oct. 7th. Probably we can consider to downgrade black to 22.8.0?

**Comment by scarrazza** [comment]
Yes, please go ahead.
