### ISSUE TITLE
Autocalibration

### ISSUE THREAD

**Issue by aorgazf** [qiboteam/qibocal#210]

**Comment by scarrazza** [comment]
@igres26 @andrea-pasquale @stavros11 I would like to use this issue to propose an implementation for the autocalibration procedure. Could you please summarize the code status for this task?

**Comment by andrea-pasquale** [comment]
I guess we can close this or should I put the roadmap from my slides here, @scarrazza?

**Comment by scarrazza** [comment]
We can close and point to #336 for reference, thanks.
