### ISSUE TITLE
Linux path being used in _base.py

### ISSUE THREAD

**Issue by maxhant** [qiboteam/qibocal#212]
For debugging purposes, someone might want to use `qibocal` on their local machine, which might be a windows. The forward slash is used in `_base.py`. Here is an example:
https://github.com/qiboteam/qibocal/blob/e4c7eaaf4f1cf2f50cca0041d93155563b475454/src/qibocal/cli/_base.py#L197-L198

**Comment by scarrazza** [comment]
We should prefer `pathlib` instead of hardcoded paths.

**Comment by DavidSarlle** [comment]
fixed in PR #236
