### ISSUE TITLE
Directory re-arranging for fitting methods

### ISSUE THREAD

**Issue by maxhant** [qiboteam/qibocal#218]
Each characterization has its own file, and so do the plots. Why wouldn't we do the same thing for the fitting methods which are getting longer, and will become increasingly more complex?

**Comment by andrea-pasquale** [comment]
Unless the situation changes with the addition for two qubits gates routines the code looks perfectly fine to me now.

**Comment by andrea-pasquale** [comment]
With the new layout the fitting for each routine is included in the same file with the data acquisition and the plotting.
