### ISSUE TITLE
Fitting data missing from html report

### ISSUE THREAD

**Issue by stavros11** [qiboteam/qibocal#247]
#232 changed the way the fitting parameters are returned by the plot routines and now they are shown as a table instead of a legend in the plotly figures. This was made to work with qq-live, however it was not ported in the static report (index.html). 

It is useful to port the fitting data to the static report too, because the report provides additional functionalities (can be shared with others, can be uploaded with qq-upload) and also some people (like me) don't use qq-live.

Note that this is not very trivial to fix because the fitting data table is generated by dash, while to get it in the static report we would need to port it to the html template.

**Comment by DavidSarlle** [comment]
@stavro I have fixed the issue in the PR #243
