### ISSUE TITLE
Tests for all calibration routines

### ISSUE THREAD

**Issue by stavros11** [qiboteam/qibocal#255]
Now that the `DummyPlatform` works with all routines, it would be great to have tests for all calibrations, including the report generation, which would confirm that plotting and fitting does not fail. 

I am not sure how this is connected or may be affected by the efforts on autocalibration, but at least for the current manual approach it would help us avoid many bugs.

**Comment by andrea-pasquale** [comment]
This has been implemented by #279.
@stavros11 if you agree we can close this issue.
