### ISSUE TITLE
Small changes for niGSC part

### ISSUE THREAD

**Issue by wilkensJ** [qiboteam/qibocal#257]
- [ ] @andrea-pasquale  Move the function outside of the `ActionBuilder` (from Stavros comment https://github.com/qiboteam/qibocal/pull/239#discussion_r1109506630): 
https://github.com/qiboteam/qibocal/blob/a9db19a388a8e563b57a33fc329151befdde4b9d/src/qibocal/cli/builders.py#L167-L173
And  @wilkensJ  reuse it instead of https://github.com/qiboteam/qibocal/blob/a9db19a388a8e563b57a33fc329151befdde4b9d/src/qibocal/calibrations/niGSC/basics/utils.py#L13-L14
- [ ] @wilkensJ  Move the imports out of the functions (as Stavros suggested here https://github.com/qiboteam/qibocal/pull/239#discussion_r1109442966 )
- [ ] @wilkensJ  Change types if necessary https://github.com/qiboteam/qibocal/pull/239#discussion_r1109487240

**Comment by andrea-pasquale** [comment]
@wilkensJ shall we close this issue?

**Comment by wilkensJ** [comment]
Yes, thank you Andrea!
