### ISSUE TITLE
Automated runner: exceptional flow

### ISSUE THREAD

**Issue by alecandido** [qiboteam/qibocal#264]
- [x] statuses (`Normal`, `Exceptional(id)`, `Broken`)
- [x] handlers.py file

more:
- [ ] agents (qubits) for multiplexing

**Comment by andrea-pasquale** [comment]
@alecandido shall we close this given that #668 got merged?
Perhaps we can open an issue with what we should do next regarding this topic.

**Comment by alecandido** [comment]
>  * [ ]  agents (qubits) for multiplexing

The missing part is multiplexing, but I feel that we're not yet ready for that. Maybe you could open an issue to keep track, but nothing else.

**Comment by alecandido** [comment]
> Let me close the issue now and as soon we have a proposal I will open a dedicated issue.

It's fine

However, in general, you could open issues even to remind things that have to be done. If we had external users, I'd also have opened it in this case, to tell that is on-track (but we don't have any, and we know we'll come back to it).

**Comment by andrea-pasquale** [comment]
Done https://github.com/qiboteam/qibocal/issues/702
