### ISSUE TITLE
Actions and acyclique graphs

### ISSUE THREAD

**Issue by maxhant** [qiboteam/qibocal#28]
Hi, 
QCVV is well designed to do no-code diagnostics. However, this design choice makes it hard to link routines together. 

## Example of dummy acyclic graph 
This logic between routines is what I refer to as an acyclic graph. Let's take a simplified example to get an idea: 

To characterize the chip, we would do:

1. Resonator spectroscopy
2. Qubit spectroscopy
3. Rabi

From there, we have a 1 qubit gate. However, the next step is to refine the qubit's frequency with Ramsey. 

4. Ramsey 

If for any reason, the qubit's frequency shifts. The detection of this frequency shift would be done by a `check_state` function which is a quick scan that verifies that the chip is in spec. 
Once it is triggered, it would see which node is the acyclic graph needs repair with `check_data`. In the case of qubit's frequency, it will depend on Step 2 and 4, so it will run this quick scan on step 2 and 4. If Step 2 is ok, then Step 4 should not be (and you check), you then run `calibrate` all the later nodes.

This dependence between nodes is the reason why it is called acyclic.

Anyway, please **read this paper which is much more detailed while being very short**:
# https://arxiv.org/pdf/1803.03226.pdf

## Server to host it

I imagine that we would have a server running on Reem that would continuously send `check_state` to various tolerances' values. It will then update the report. This report could look like an acyclic graph, showing different colours depending on the state of the nodes. (see example in the paper). 
One could click on the node to see the data and history. 

It could also alert users if their program ran while the chip might have been out-of-spec. It could also alert experimentalists if the calibration is unsuccessful. 

## Architecture of QCVV for that

One could imagine the server/ algorithm creating ONE action runcard, that I will now call actioncard, that will include many pre-saved indivividual action runcards, that I will now call actions, based on the acyclic graph. This could be `check_state`, `check_data` or `calibrate` actions. 

These actions will include fitting, saving and updating the runcard (the qibolab one). The runcard will contain a lot more information like thresholds, tolerances etc... It will also need to contain the data last registered to each node because `check_data` will overlay its points and check if they are within an acceptable range. 

At this stage, I will then dissociate this runcard into the instrument runcard from the qcvv runcard. The former, in qibolab, will contain the instruments parameters and the native gates. It will be lite. The latter, in qcvv, will contain the data from the nodes, the thresholds for each node, the thresholds for the specs etc... 

We need the code to generate that master actioncard, and a way to store the dependence between nodes.

## Remarks

I am probably missing a few things. 
Maybe it is best if we start from something existing to avoid missing out on features. Here are a few non-exhaustive examples that I found online very quickly: 
https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=9477114
https://github.com/climech/grit
https://airflow.apache.org/docs/apache-airflow/2.3.2/concepts/dags.html

**Comment by andrea-pasquale** [comment]
@maxhant shall we close this issue?

**Comment by maxhant** [comment]
I still think that it is quite relevant, especially now that we are implementing it on main. 
Not all the functionalities discussed in that paper are added in the autocalibration. What do you think?

**Comment by andrea-pasquale** [comment]
I just thought about closing this since we already have a roadmap in mind for the autocalibration.
We can keep it as a reference, no problem.
