### ISSUE TITLE
Implement new data structure for protocols

### ISSUE THREAD

**Issue by andrea-pasquale** [qiboteam/qibocal#335]
Things to be changed for data structure:

- [x] Fix data attribute in task.py  _Originally posted by @AleCandido in https://github.com/qiboteam/qibocal/pull/279#discussion_r1192376813_ #406
- [x] Drop pint and move to np.array
~~Support for multiple formats (?)~~
- [x] Add possibility to generate report from stored data instead of `History` . This will require to save the fitted parameters alongside the raw data (unless we also rerun the fitting when we generate the report). #406

**Comment by AleCandido** [comment]
Turn this issue in a broader one, spanning all the data related points (e.g. start importing those in #336).

We will solve this in the close future, in a dedicated data-oriented PR.

**Comment by andrea-pasquale** [comment]
Closed by #406
