### ISSUE TITLE
Current Ramsey fitting bug

### ISSUE THREAD

**Issue by DavidSarlle** [qiboteam/qibocal#337]
@andrea-pasquale @DaniloKolesnyk @Edoardo-Pedicillo @aorgazf  I have being testing the Ramsey fitting and to me seems that the delta_phys calculated in the fitting should be subtracted in qubit_frequency instead of added. 

![imagen](https://github.com/qiboteam/qibocal/assets/39095664/bd5751bf-9ba2-4cea-962d-5ef58770b57c)

If you check the reports below, you will see that, after running multiple ramsey, if the delta_phys is subtracted, the delta_phys tends to decrease. If the delta_phys is added, it tends to increase in each iteration.

(+ delta_phys)
[multiple ramsey detuned (delta +).pdf](https://github.com/qiboteam/qibocal/files/11495292/multiple.ramsey.detuned.delta.%2B.pdf)

(-delta_phys)
[multiple ramsey detuned (delta -).pdf](https://github.com/qiboteam/qibocal/files/11495298/multiple.ramsey.detuned.delta.-.pdf)

**Comment by DavidSarlle** [comment]
> 

@igres26 I did not detune the qubit frequency manually. The qubit frequency used was the one obtained from the qubit spec.
The number of oscilations was 10. Do we have to check the number of oscilations introduced by the user in order to be sure that the induced change of frequency from the oscillations is larger than the detuning due to miscalibration?

**Comment by igres26** [comment]
I see what is wrong now. The `delta_phys` is computed with the right sign under the conditions I stated. But then the `corrected_qubit_frequency` should subtract the `delta_phys` to recover the real frequency.

**Comment by DavidSarlle** [comment]
> I see what is wrong now. The `delta_phys` is computed with the right sign under the conditions I stated. But then the `corrected_qubit_frequency` should subtract the `delta_phys` to recover the real frequency.

That was exactly what I was suggesting, because the reports are quite clear. If we substract the delta_phys to recover the real frequency, the next Ramsey iterations are reducing the physical detunning.
I was not talking about the sign when computing the delta phys, but about the sign when reconstructing the qubit freq.

**Comment by igres26** [comment]
Yep. You are right. I asked @andrea-pasquale to re-check the tests he did, since they shouldn't have worked in the first place to make sure we are not missing anything. But the found Delta should always be subtracted to recover the real frequency.

**Comment by andrea-pasquale** [comment]
I've rerun Ramsey on the RFSoC with the two signs by changing the qubit frequncy by +0.5 MHz.
The first ramsey has 5 oscillations while the second one has 3 oscillations.
This is the current version that we have in main
![ramsey_old_sign](https://github.com/qiboteam/qibocal/assets/49183315/cb6162ad-569f-41fd-b108-547bf4a6e61c)

This is the version with the other sign:
![ramsey_new_sign](https://github.com/qiboteam/qibocal/assets/49183315/2afed1c8-bb77-420b-a5a9-8818ea17d434)

For the RFSoC the current sign is correct. I think that this is the case because even if the new frequency is qubit_freq + delta_freq the result is correct because delta_freq < 0.
A possible solution to be consistent could be to fix delta_freq to be positive during the fitting and then we should put a minus sign. I will test with qblox now.
What do you think @igres26 and @DavidSarlle?

**Comment by igres26** [comment]
Double-check things, as 4 oscillations in 2000 ns is a detuning of 2 MHz, which compared with 3 oscillations should be 1.5 MHz, therefore yielding a delta_phys of +0.5 MHz. Which then should be subtracted. Can you check why you get a - sign if the detuning seen is higher than the number of oscillations you put?

**Comment by DavidSarlle** [comment]
@igres26 thanks for testing. I understand. For the moment (while we debug if we can do something with the phase at the level of the driver) we can modify Ramsey routine  to return only the delta_phys and in qibolab, depending on the platform, add or subtract the delta to the current qubit freq during the update method. This modification will not affect any driver... What do you think @andrea-pasquale @igres26 @aorgazf ?

**Comment by andrea-pasquale** [comment]
I think that this should be ok for now.

**Comment by andrea-pasquale** [comment]
I believe that with the latest version of qblox also this issue has been fixed.
