### ISSUE TITLE
High level characterization in qibocal, a little summary

### ISSUE THREAD

**Issue by wilkensJ** [qiboteam/qibocal#352]
A little presentation aiming at pointing out the features the high level characterization part needs that have to be discussed about. Created by @vodovozovaliza and @wilkensJ. 

![qibocal_report_flow 001](https://github.com/qiboteam/qibocal/assets/70592365/3fdc5709-850c-4836-af02-3c2990e5a0f7)
![qibocal_report_flow 002](https://github.com/qiboteam/qibocal/assets/70592365/68cc7985-4b2a-4308-bc1e-3ec792d85532)
![qibocal_report_flow 003](https://github.com/qiboteam/qibocal/assets/70592365/6662cde9-6e2c-4eac-8e14-2206933ef25c)
![qibocal_report_flow 004](https://github.com/qiboteam/qibocal/assets/70592365/86b16c1a-a8c7-4a35-a19e-e8954f730414)
![qibocal_report_flow 005](https://github.com/qiboteam/qibocal/assets/70592365/190a0de9-7f78-4538-b01d-104999770e79)
![qibocal_report_flow 006](https://github.com/qiboteam/qibocal/assets/70592365/ef9caaf8-5b5f-45d6-a2af-4ef42b2ea150)
![qibocal_report_flow 007](https://github.com/qiboteam/qibocal/assets/70592365/1916016f-fab9-417b-8c54-5b3b07fb7d7a)
![qibocal_report_flow 008](https://github.com/qiboteam/qibocal/assets/70592365/a2380f46-df06-4c75-9f37-45ae8302056b)

![qibocal_report_flow 009](https://github.com/qiboteam/qibocal/assets/70592365/af81fdf9-8e02-4cf7-9756-c913dfd157e6)
 
![qibocal_report_flow 010](https://github.com/qiboteam/qibocal/assets/70592365/905b2fba-96a9-4655-9cd7-6ec654fca78b)

![qibocal_report_flow 011](https://github.com/qiboteam/qibocal/assets/70592365/b5e4dc3e-616c-452e-adb3-13fd09a3849d)

![qibocal_report_flow 012](https://github.com/qiboteam/qibocal/assets/70592365/f17e173d-e068-43a8-bf47-43ee493638e9)
![qibocal_report_flow 013](https://github.com/qiboteam/qibocal/assets/70592365/4c4573c4-8228-4a49-a241-acef6588cccc)
![qibocal_report_flow 014](https://github.com/qiboteam/qibocal/assets/70592365/85373302-52fa-4b7e-8ef0-145341bd616b)
![qibocal_report_flow 015](https://github.com/qiboteam/qibocal/assets/70592365/240b8487-163a-439d-a114-ef43d74797a5)
![qibocal_report_flow 016](https://github.com/qiboteam/qibocal/assets/70592365/08c729ec-9886-4122-aa9d-555d7c85d22c)

![qibocal_report_flow 017](https://github.com/qiboteam/qibocal/assets/70592365/624146bd-1274-4312-9c1f-36be79b41788)
![qibocal_report_flow 018](https://github.com/qiboteam/qibocal/assets/70592365/6085e811-faae-4758-8806-5e9652a962ef)
![qibocal_report_flow 019](https://github.com/qiboteam/qibocal/assets/70592365/dd363160-7820-43f9-832d-135cb783b266)

**Comment by andrea-pasquale** [comment]
I'm closing this since there are other issues #353 #354 #355 and     #356 with the same content
