### ISSUE TITLE
API to acquire, access (and analyze) the data and results

### ISSUE THREAD

**Issue by wilkensJ** [qiboteam/qibocal#356]
From the presentation in this issue #352. 

More details
------------
The _ methods (`_acquisition`,` _fit`, `_plot`) are not accessible easily from the outside. Also ensembles/methods can be shared between modules. For the example above, different set ups of scans can be chosen which would not change anything in the remaining part of the code. Or a different extract method. Or a different plot method.

Why
----
Make development and contributing easier

Suggestions
-------------
A more atomic approach, split the `_acquisition` method into a set up scan and execute scan (if possible, probably only for high level characterizations), make them obviously accessible and encourage developers to use this feature. If a routine is settled and stable it should be then added to the auto calibration process.

![qibocal_report_flow 011](https://github.com/qiboteam/qibocal/assets/70592365/7d6dddc4-adcf-4d37-b10b-6fc9001de1b7)

**Comment by andrea-pasquale** [comment]
Available soon in the latest version of the documentation #573
