### ISSUE TITLE
pyyaml is not automatically installed by poetry 

### ISSUE THREAD

**Issue by ingoroth** [qiboteam/qibocal#362]
When importing qibocal after poetry install, it complains that yaml can not be imported. 

I guess pyyaml dependency is missing in pyproject.toml

**Comment by andrea-pasquale** [comment]
Hi @ingo,  thanks for opening this issue.
From GitHub actions everything seems fine to me.
Are you using the latest main or another branch?

**Comment by ingoroth** [comment]
Hi, I just freshly cloned and poetry installed from main.

**Comment by andrea-pasquale** [comment]
Could you please try with a fresh environment to see if you can reproduce the issue?
Was this error triggered during installation or for a specific application?

**Comment by Edoardo-Pedicillo** [comment]
@ingoroth can we close this issue?

**Comment by andrea-pasquale** [comment]
Even if I didn't see this issue personally I think that @AleCandido might have fixed the problem by adding `pyyaml` explicitly as a dep in https://github.com/qiboteam/qibocal/commit/0dae1fdde4b34648ce0b52a1bbb70022edf3de90.
I will close it now, if the issue persist we can reopen the issue.
