### ISSUE TITLE
niGSC tests fail with Qibo 0.1.14 

### ISSUE THREAD

**Issue by Edoardo-Pedicillo** [qiboteam/qibocal#377]
https://github.com/qiboteam/qibocal/actions/runs/5153461808/jobs/9280721658#step:11:2411

**Comment by wilkensJ** [comment]
Thank you @Edoardo-Pedicillo, is the qibo version for qibocal updated to the latest one? Then the tests fail because of the new implementation of the noise models.

**Comment by Edoardo-Pedicillo** [comment]
>is the qibo version for qibocal updated to the latest one? 

It will be after the merging of #376 (or another PR that updates `poetry.lock`)

>Then the tests fail because of the new implementation of the noise models.

Can you fix them?

**Comment by wilkensJ** [comment]
Can you point me to the PR which updates the version? Then I can push the changes to that branch so that it is synchronized.

**Comment by Edoardo-Pedicillo** [comment]
The PR is #376
