### ISSUE TITLE
Migrate 2q CZ tune transition (chevron) and tune landscape routines to autocalibration

### ISSUE THREAD

**Issue by aorgazf** [qiboteam/qibocal#379]
Hi @Edoardo-Pedicillo, @andrea-pasquale 
Could you please migrate these routines into autocalibration.
In this branch I have them working and they include some enhancements and fittings:
https://github.com/qiboteam/qibocal/tree/alvaro/qblox9_sweepers

**Comment by andrea-pasquale** [comment]
Thanks @aorgazf for opening the issue.
I'm aware of the fact that we still need to port some routines to new layout.
For the migration I would prefer to port what we currently have in main given that it has been tested and approved by multiple people.
Could you please open a small PR with the enhancements and  the fitting for those routines?
