### ISSUE TITLE
Implement `from_action` constructor

### ISSUE THREAD

**Issue by andrea-pasquale** [qiboteam/qibocal#386]
_Originally posted by @AleCandido in https://github.com/qiboteam/qibocal/pull/351#discussion_r1219094880_

**Comment by andrea-pasquale** [comment]
I think that this is more or less what `Executor.create` is doing. Shall we close it @alecandido ?

**Comment by alecandido** [comment]
What the comment was referred to was exactly
https://github.com/qiboteam/qibocal/blob/d2cae9702a0f711a21fcdc117c75f707fdc87fd8/src/qibocal/auto/task.py#L35-L38

I then linked this to #870
