### ISSUE TITLE
Save the fitting

### ISSUE THREAD

**Issue by Jacfomg** [qiboteam/qibocal#395]
For the #383 I need to save from the fitting part a numpy array on the report. But I would say that this can be useful in general.

**Comment by AleCandido** [comment]
The goal has always been that the acquired data and fitting results should be saved on disk. Always :)

So, in this sense, this should be aligned with #372 and its follow-ups.

**Comment by andrea-pasquale** [comment]
Great!
I propose `yaml` or `json` given that I'm planning to convert the dataclass `Results` into a dictionary and from there I thought that `yaml` or `json` could be a valuable option.
Since we are refactoring between the two which is more adapt given what we need to do?

**Comment by andrea-pasquale** [comment]
Thanks for the detail explanation @AleCandido!
