### ISSUE TITLE
Time of flight and smearing fitting

### ISSUE THREAD

**Issue by Jacfomg** [qiboteam/qibocal#416]
I'm still investigating this routine #402, it seems that it's best to send powerful pulses not at the readout frequency at least for the chip I used.

The fitting is still very tricky becuase of the high frequency oscillations on the signal and the oscillations on the readout pulse. Those need to be detected and fitted for the smearing value (marked red samples). Any advice ?

![image](https://github.com/qiboteam/qibocal/assets/19141117/2b0ee0fc-1232-4a60-b04d-f403960ed774)

**Comment by andrea-pasquale** [comment]
If the main problem are the oscillations what about using FFT to remove them?
See for example [here](https://stackoverflow.com/questions/39799821/how-to-remove-frequency-from-signal).

**Comment by Jacfomg** [comment]
The problem is that @rodolfocarobene didn't see these oscillations, just some small noise. I still not sure until we test more instruments or devices if it's only happening for 2D resonators

**Comment by andrea-pasquale** [comment]
Closing this in favor of #876.
