### ISSUE TITLE
Quantum non-demolition-ness of the readout pulse

### ISSUE THREAD

**Issue by Jacfomg** [qiboteam/qibocal#420]
We need a way of checking the quantum non-demolition-ness of our readout pulse before trying to play with #399. I propose trying to implement the scheme presented https://arxiv.org/abs/2106.06173.

**Comment by andrea-pasquale** [comment]
Sounds good to me. Are you planning to implement this experiment, right?
![image](https://github.com/qiboteam/qibocal/assets/49183315/f7bdbd04-5d11-478d-9289-b20d1de0c7ab)
It could also be nice to compute the fidelity which should be equal to the one computed from the classification experiment.

**Comment by Jacfomg** [comment]
Yes, that would be the first idea when I get some spare time.

**Comment by Jacfomg** [comment]
Not mine at least, but the devices do.

**Comment by andrea-pasquale** [comment]
> Not mine at least, but the devices do.

Is this available for qm, qblox or the rfsoc? @rodolfocarobene @stavros11 @aorgazf

**Comment by Jacfomg** [comment]
Working for some new routine with is a quantum Zeno prototype. I will try to finish the routine and open PR for the Zurich fix and that routine first.
![imagen](https://github.com/qiboteam/qibocal/assets/19141117/e50b8709-b9a6-41e2-957f-6f6c39a5a2f3)

**Comment by Jacfomg** [comment]
Btw, this is doing the same with 1 shot. You can see readout pulse 40 or around that excited the qubit. I don't know up to what extend this is expected.

![imagen](https://github.com/qiboteam/qibocal/assets/19141117/b8809f15-f744-4cc5-b820-d0f975a4f48b)

**Comment by Jacfomg** [comment]
It's destructive :)

![image](https://github.com/qiboteam/qibocal/assets/19141117/1e476d83-66a9-443e-a378-4b75f7c0884c)
