### ISSUE TITLE
Resonator and Qubit Flux Spectroscopy Matrices

### ISSUE THREAD

**Issue by aorgazf** [qiboteam/qibocal#467]
Hi,
It would be nice to extend the functionality of the flux spectroscopy routines to not only show the elements of the diagonal (how the frequency of a resonator/qubit changes with the flux applied to that qubit) but the entire matrix.
The fitting of the off diagonal elements will require a different function, but it should provide the coefficient of the crosstalk matrix. 
This matrices will allow us to see the crosstalk between fluxlines and the avoided crossings between qubits. These avoided crossings can later be used,in conjunction with the chevron, to characterise 2q gates.

This functionality was implemented in my branch [src/qibocal/calibrations/characterization](https://github.com/qiboteam/qibocal/tree/alvaro/qblox9_sweepers), but never ported to the latest format of qibocal.
![image](https://github.com/qiboteam/qibocal/assets/55031026/3739938d-e194-4efd-9eea-4a148f689af4)

**Comment by andrea-pasquale** [comment]
Closed by #470

**Comment by stavros11** [comment]
@andrea-pasquale regarding these issues, I believe we are still missing the fitting, ie the numerical calculation of the crosstalk matrix (not just the plots), but as we discussed in the other PR this may not be easy given that avoided crossings may appear.

**Comment by andrea-pasquale** [comment]
Yes, I know that we are missing the fitting. I was going through issues and I decided to close this one given that the major problem was having a protocol which could show how each qubit is affected by moving the flux of another qubit.
Eventually we can open another issue for just the crosstalk matrix.
