### ISSUE TITLE
Resonator Tracking for Qubit Flux Spectroscopy

### ISSUE THREAD

**Issue by aorgazf** [qiboteam/qibocal#469]
Hi @DavidSarlle,
The current implementation of qubit flux spectroscopy does not adjust the readout frequency to track the dressed frequency of the resonator.
As you know, the application of flux to the qubit shifts its frequency, and in turn, the frequency of the resonator.
This limits the extent in which the experiment can be run, to a small section around the sweetspot, preventing us, for example, seeing avoided crossings that take place further away from the sweetspot.
Below is an example of what we currently have. Beyond a certain flux value, the dressed frequency of the resonator has shifted so much that we are always measuring a high value (corresponding to the yellow bands at the top and bottom).
![image](https://github.com/qiboteam/qibocal/assets/55031026/60e240d2-54ce-4293-909c-72c0f5433522)
You and @maxhant had coded different solutions to track the resonator, fitting a polynomial or interpolating between the peaks at discrete flux levels. But the latest version of the resonator spectroscopy flux fits the actual equation that governs the shift and produces all the parameters.
It would be nice to implement the tracking of the frequency using that formula and those parameters if they are available in the runcard.

**Comment by andrea-pasquale** [comment]
Closed by #519
