### ISSUE TITLE
Flux Crosstalk Matrix

### ISSUE THREAD

**Issue by aorgazf** [qiboteam/qibocal#470]
Hi,
The current implementation of the resonator spectroscopy flux produces the coefficient Cij of the flux crosstalk matrix.
This matrix will allow us to control the frequencies of each qubit accurately. By multiplying the vector of frequencies desired by the matrix, one will obtain a vector of biassing currents to be applied to each flux line.

We need to build the matrix using the results of the resonator flux spectroscopy, and prepare an experiment that allowed us to verify that the matrix and its application work correctly.
The experiment resembles a qubit spectroscopy flux, but instead of sweeping flux, we weep a qubit frequency and measure the impact on the rest of the qubits.
If the matrix and its application is correctly implemented, sweeping on qubit frequency should not affect any of the others. 
If we want to be able to execute 2q gates and single qubit gates in parallel, this feature is essential.

**Comment by andrea-pasquale** [comment]
Closed by #462
