### ISSUE TITLE
Intuitive color map for Chevron routine

### ISSUE THREAD

**Issue by aorgazf** [qiboteam/qibocal#471]
Hi,
The current color maps applied to the chevron plots, in my opinion, should be reversed.
![image](https://github.com/qiboteam/qibocal/assets/55031026/d4ab87de-2f40-434a-856e-2364f8ff078e)

Typically, brighter colors are used for high values, and darker colors for low values.
I would also swap the hues between the high frequency qubit and the low frequency one.

**Comment by andrea-pasquale** [comment]
Fixed in #520
