### ISSUE TITLE
2q gates - Add second excited state to classify states

### ISSUE THREAD

**Issue by aorgazf** [qiboteam/qibocal#477]
Hi,
The current implementation of `single_shot_classification` only caters for states |0> and |1>.
Now that we can calculate the anharmonicity and find the 2-phonton transition w02, it would be nice to extend the experiment to excite also the second state and determine a classification boundary between the three states.
Being able to determine the percentage of excitations to state 2 would allow us to optimise our 2q CZ gates.

**Comment by andrea-pasquale** [comment]
Closing this as implemented in #543
