### ISSUE TITLE
StdRB + Transpiler issue

### ISSUE THREAD

**Issue by Jacfomg** [qiboteam/qibocal#484]
Std RB gets an error on the transpiler file. It happens with both Zurich and Qblox. It happens when the 1st circuit it's getting executed and the routine fails. However, running circuits on a simple example seemed to work. Might it be something related to the topology ?

@wilkensJ @stavros11 could you take a look ?

**Comment by andrea-pasquale** [comment]
Fixed in main:
https://github.com/qiboteam/qibocal/blob/aabc7f0771df43e7f5c39b9b4b2087b3c4a24f49/tests/test_randomized_benchmarking.py#L171
