### ISSUE TITLE
Parameters update in Resonator Spectroscopy Flux

### ISSUE THREAD

**Issue by aorgazf** [qiboteam/qibocal#500]
Hi,
The following parameters extracted from resonator spectroscopy flux routine are currently not being updated in the runcard:

Xi
d
g
Ec
Ej
bare_resonator_frequency
f_qs
f_r_offset
C_ii

These parameters need to be stored so that they can be used later on to track the frequency of the resonator as a function of the flux applied.

**Comment by andrea-pasquale** [comment]
I believe this was already addressed by #519 and #538
