### ISSUE TITLE
allXY still not working in iqm

### ISSUE THREAD

**Issue by DavidSarlle** [qiboteam/qibocal#598]
allXY is still not working in iqm. After the fix introduced by @andrea-pasquale now it looks like:

![image](https://github.com/qiboteam/qibocal/assets/39095664/28dd5e9a-32d8-457d-b9ac-e676a9c9849f)

Seems that no results for all the pais of gates are shown anymore...

**Comment by DavidSarlle** [comment]
@Jacfomg or It is still a driver problem or It is a qibocal bug introduced in latests changes. Why are you assigning the issue too me?

**Comment by andrea-pasquale** [comment]
I was debugging the AllXY with @stavros11 and @Jacfomg a week ago. I pushed some changes single the code was not working with qlbox which broke zh driver. I believe that this is mostly a qibolab issue. We should make sure that all drivers return exactly the same type of output (mostly the shape of the array) for all the different execution and acquisition mode that we have in qibolab.

**Comment by Edoardo-Pedicillo** [comment]
Closed because https://github.com/qiboteam/qibolab/issues/647
