### ISSUE TITLE
Cannot install with pip (data.homepage must be uri)

### ISSUE THREAD

**Issue by GabrielePalazzo** [qiboteam/qibocal#603]
When trying to install `qibocal` with `pip` an error is raised, stating that `homepage` and `documentation` in `pyproject.toml` must be URL strings.

**Comment by scarrazza** [comment]
Indeed, conda has also identified this issue https://github.com/conda-forge/qibocal-feedstock/pull/4. I have just pushed to main the url, could you please give a try?

**Comment by andrea-pasquale** [comment]
I tried just now and everything seems fine.

**Comment by GabrielePalazzo** [comment]
`pip install -e .` fails on `main` on my consiguration on the cluster. Is it just me, then?

**Comment by andrea-pasquale** [comment]
I can confirm that it fails I thought that you were talking about the installation of the new release.
