### ISSUE TITLE
Improve spectroscopy fit

### ISSUE THREAD

**Issue by GabrielePalazzo** [qiboteam/qibocal#612]
- [ ] Make Lorentzian fit less dependent on initial guesses.
- [ ] Optimize Lorentzian fit, e.g. change fit bounds on the x axis.
- [ ] Try other methods, e.g. NN.

**Comment by Edoardo-Pedicillo** [comment]
@GabrielePalazzo, Do you think the proposal in #784 could close this issue ?

**Comment by GabrielePalazzo** [comment]
> @GabrielePalazzo, Do you think the proposal in #784 could close this issue ?

Yes. We should still think about adding some kind of skewness to the Lorentzian, but for sure it will be an improvement.

**Comment by andrea-pasquale** [comment]
I think that this issue can be closed given that we merged #917
