### ISSUE TITLE
spin_echo_msr name

### ISSUE THREAD

**Issue by aorgazf** [qiboteam/qibocal#614]
Hi,
currently `spin_echo_msr` runs using for loops. for consistency, I believe it should be called `spin_echo_sequences`

**Comment by andrea-pasquale** [comment]
Thanks for opening the issue.
Fine, we can change the name. Could you please give it a try @GabrielePalazzo ?

**Comment by GabrielePalazzo** [comment]
> Thanks for opening the issue. Fine, we can change the name. Could you please give it a try @GabrielePalazzo ?

Sure.

**Comment by andrea-pasquale** [comment]
@GabrielePalazzo we can close this issue since you fixed in #611, right?
