### ISSUE TITLE
Drop Numba (if possible)

### ISSUE THREAD

**Issue by AleCandido** [qiboteam/qibocal#637]
Numba is a mandatory dependency in Qibocal:
https://github.com/qiboteam/qibocal/blob/8decaec48af4dc166bf69c6ebd1d20a7950d86e9/pyproject.toml#L52-L55
(btw, please lift mandatory ones above the optional ones)

However, it is used only in a single place:
https://github.com/qiboteam/qibocal/blob/8decaec48af4dc166bf69c6ebd1d20a7950d86e9/src/qibocal/protocols/characterization/utils.py#L248-L264

We should try to rewrite `cumulative` in pure NumPy (avoiding the `for` loop, the only non-NumPy operation), and drop the whole dep on Numba.

Consider that Numba is coming with the whole `llvmlite`, that is a full-blown compiler on its own...

**Comment by andrea-pasquale** [comment]
Thanks for opening the issue @AleCandido.
We decided to go with numba when we were accelerating this `cumulative` function.
We also tried to use just numpy but the performance was better with numba as expected.
For me it is fine to drop numba, but first we should to a quick benchmark with the values that we expect to use with this function (around 1e3 - 1e6 points). Also if there is a shortcut to compute the cumulative we could use directly that if the performance is good enough for us.

**Comment by AleCandido** [comment]
I raised the issue to make the developers aware of it, and show the criticalities of the present approach (I was reviewing Qibocal dependencies in general).
It doesn't have to be solved immediately, it's definitely more of a long term one (it's mostly a maintainability issue).

Numba should not accelerate NumPy operations, they are already optimized enough. Of course, the composition of many operations might be optimized, but I do not believe has much heuristic to discriminate about NumPy usage (maybe I'm wrong).

Instead, if you see an advantage, I believe it should be just because of the loop.
So, I was really thinking about a reimplementation. But I should read it more carefully to find a way to reimplement it (usually this kind of things are non-trivial, but possible, with NumPy).
