### ISSUE TITLE
Punchout plot does not appear

### ISSUE THREAD

**Issue by stavros11** [qiboteam/qibocal#641]
I think something in the punchout plot was broken in one of the latest merges (possibly #627, but I am not sure at all). When I run with `qq auto` the plot does not appear in the report, even though no error raised. When I run with `qq acquire` + `qq report` the plot appears normally. So maybe the fitting breaks something?

**Comment by andrea-pasquale** [comment]
Thanks @stavros11 for opening the issue, #642 should fix this.
Given that we merge some PRs when we did not have access to the hardware I expected that there could be some bugs.
