### ISSUE TITLE
Problem displaying dispersive shift

### ISSUE THREAD

**Issue by JavierSerranoGarcia** [qiboteam/qibocal#646]
I am trying to do a dispersive shift but one of the plots is not shown ...

![image](https://github.com/qiboteam/qibocal/assets/9057076/f20ced74-d256-4008-a6ef-c36efe9be18c)

Attached you will find the data generated by the routine.

[20231129__disp_shift.zip](https://github.com/qiboteam/qibocal/files/13497003/20231129__disp_shift.zip)

**Comment by andrea-pasquale** [comment]
Thanks @JavierSerranoGarcia for opening the issues.
#647 should fix the problem with the plot.
