### ISSUE TITLE
fix scheme in frontpage documentation

### ISSUE THREAD

**Issue by scarrazza** [qiboteam/qibocal#661]
Text in the frontpage documentation svg is incorrectly rendered:

![image](https://github.com/qiboteam/qibocal/assets/10464827/101a800d-e875-4545-81f1-c2ad30145722)

**Comment by andrea-pasquale** [comment]
I tested on several browsers and this issue seems to be appear only on firefox and safari, on chrome and edge it seems to be fine. On mobile the image is wrong also.  Maybe converting it to a png instead of a svg could help (?)

**Comment by scarrazza** [comment]
@MatteoRobbiati could you please double check?
