### ISSUE TITLE
Fit of resonator flux hangs

### ISSUE THREAD

**Issue by stavros11** [qiboteam/qibocal#663]
I am not sure if that is platform dependent or a general problem but when running on qw5q_gold (using qibolab, qibocal and platforms_qrc main) the resonator flux routine hangs, I believe, on the fitting part (but could also be the plotting). 

If I cancel (Ctrl+C) the job and then do `qq report` on the acquired data I get the report properly.

**Comment by andrea-pasquale** [comment]
I think I saw this issue before. 
Since we now that the fitting is very unstable I suggest you to run using `qq acquire` and to generate the report afterwards using `qq report`.
