### ISSUE TITLE
Option to keep job alive if a routine fails

### ISSUE THREAD

**Issue by stavros11** [qiboteam/qibocal#671]
While working on https://github.com/qiboteam/qibolab_platforms_qrc/pull/73 I noticed the following things that may be useful in other applications:
1. We could have an option in `qq auto` (and maybe `qq acquire`), similar to `--no-update`, that keeps the execution alive and goes to the next routine if one of the routines fails. I think now the whole job will stop if a routine fails. I am not sure if there is a clean way to implement this other than the ugly try-(global) except.
2. Completely unrelated to 1: the [function that uploads reports](https://github.com/qiboteam/qibocal/blob/5f101333aeef1d589f5f7c3875a20477978d37b5/src/qibocal/cli/upload.py#L26) currently uses logging to print the url and returns nothing. It could be useful to return at least the url as a string, for applications that use this as part of a Python script, not via the `qq upload` cli, and would like to pass the url somewhere else (such as the bot post on GitHub).

Not a priority, I am not sure if there are other applications, but at least 2 is very simple to fix (just need a `return url`).

**Comment by andrea-pasquale** [comment]
> 1. We could have an option in `qq auto` (and maybe `qq acquire`), similar to `--no-update`, that keeps the execution alive and goes to the next routine if one of the routines fails. I think now the whole job will stop if a routine fails. I am not sure if there is a clean way to implement this other than the ugly try-(global) except.

I am not sure about this, for the reason that you already mentioned (`try-except`).
If we don't want to add the option we can also add another execution mode which should can be `qq brute-force` or something like that which it will do exactly what you asked for.

I also think that keeping it just in the bot might be good enough for now.



> 2\. Completely unrelated to 1: the [function that uploads reports](https://github.com/qiboteam/qibocal/blob/5f101333aeef1d589f5f7c3875a20477978d37b5/src/qibocal/cli/upload.py#L26) currently uses logging to print the url and returns nothing. It could be useful to return at least the url as a string, for applications that use this as part of a Python script, not via the `qq upload` cli, and would like to pass the url somewhere else (such as the bot post on GitHub).

I totally agree.
