### ISSUE TITLE
Sampling rate not in `Platform.settings`

### ISSUE THREAD

**Issue by PiergiorgioButtarini** [qiboteam/qibocal#680]
Hi all, I was trying to implement the `time_of_flight_readout` routine with Qblox and I saw that it requires the sampling rate.
Since from PR https://github.com/qiboteam/qibolab/pull/704 this information is no longer stored in `Platform.settings`, this should be fixed. 
I propose a possible solution in PR https://github.com/qiboteam/qibocal/pull/679, but for sure there is a better way to do it, @stavros11.

**Comment by andrea-pasquale** [comment]
Closed by #679
