### ISSUE TITLE
Function `randomized_benchmarking.circuit_tools.embed_circuit` could be deprecated

### ISSUE THREAD

**Issue by renatomello** [qiboteam/qibocal#692]
Now that the `Circuit` class admits the possibility to customize wire names, this function is redundant and could be removed by using the `Circuit.wire_names` primitive.

**Comment by Jacfomg** [comment]
I think we are not using it after #597 if I am right.

**Comment by andrea-pasquale** [comment]
> I think we are not using it after #597 if I am right.

Indeed, we can close the issue then.
