### ISSUE TITLE
RB data structure

### ISSUE THREAD

**Issue by andrea-pasquale** [qiboteam/qibocal#712]
Here is a  proposal for storing data form RB experiment.
After we merge #597 we will switch to `np.arrays`, however to be able to debug and reproduce the code some improvements could be performed.
In order to store both circuits and shots for each iteration and depth we could have something like this:

```py

@dataclass 
class RBData():

    data: dict[QubitId, Depth] = npt.NDArray[int]
    circuits: dict[QubitId, Depth]  npt.NDArray[int]

    ....

```
The idea is that for each qubit and depth we will store a matrix with dimension `Niterations` x `Shots` for `data` and
for `circuits` a matrix with dimension `Niterations` x `Depths`. For `circuits` each column will be filled with numbers in the range `0-23` that corresponds to the possible clifford single qubit gates, following the convention defined here: 
https://github.com/qiboteam/qibocal/blob/4576764a680ce23e208f647fcd8b5730f321d5bc/src/qibocal/protocols/characterization/randomized_benchmarking/utils.py#L11-L44
I believe that in this way it will be possible to easily run custom post-processing operations.

**Comment by Jacfomg** [comment]
I think we can close this with the #718

**Comment by Edoardo-Pedicillo** [comment]
:+1:
