### ISSUE TITLE
RB fits and plots

### ISSUE THREAD

**Issue by Edoardo-Pedicillo** [qiboteam/qibocal#713]
- [ ] https://github.com/qiboteam/qibocal/pull/597#issuecomment-1943245053
- [ ] https://github.com/qiboteam/qibocal/pull/597#issuecomment-1943831807

**Comment by Jacfomg** [comment]
I think we can close this with #718

**Comment by Edoardo-Pedicillo** [comment]
> I think we can close this with #718

You are right
