### ISSUE TITLE
Slow tests for rabi lenght

### ISSUE THREAD

**Issue by Jacfomg** [qiboteam/qibocal#772]
Rabi lenght signal and Rabi lenght sequences tests are really slow.

**Comment by Edoardo-Pedicillo** [comment]
I tried to run the tests and I can not reproduce the issue, could you give us more details ?

**Comment by Jacfomg** [comment]
I'm not sure what I could add ? I just ran test on qibocal main to check and it was still there for me.

**Comment by andrea-pasquale** [comment]
You can run tests on a different laptop, or create a new env.

**Comment by Jacfomg** [comment]
I did create a new env, but I saw that on another machine it stopped. I will try to reinstall everything.
