### ISSUE TITLE
Flipping detuned

### ISSUE THREAD

**Issue by igres26** [qiboteam/qibocal#789]
Similarly to Ramsey, it might be interesting to let a known detuning be in the flipping routine, so that it is easier to fix for small adjustments. 

Will that require a lot of changes?

**Comment by andrea-pasquale** [comment]
> Will that require a lot of changes?

No, I don't think so. As long as we can test on hardware it should be quite straightforward.

We already had an issue for this #761. I'm closing this as duplicate.
