### ISSUE TITLE
ZZ Crostalk Compensation Matrix and Accuracy

### ISSUE THREAD

**Issue by aorgazf** [qiboteam/qibocal#846]
Hi,
The current implementation of `qubit_crosstalk` does not yet provide the crosstalk copensation matrix so that one could calculate the set of biases to be applied to qubits as a function of a set of qubit frequencies.
Additionally, the routine measures crosstalk at the bias point defined at the runcard (typically the sweetspot and therefore the least sensitive). For more accurate results, the routine should measure crosstalk at a highly sensitive point. A highly sensitive point can be obtained from the fit of the qubit flux dependence.

The ability to quickly rearrange qubit frequencies without having to recalibrate sweetspots is essential for the characterization of QPUs with many qubits, and also very useful when performing measures at different flux points ( for example T1 and T2 at various points )

**Comment by andrea-pasquale** [comment]
Thanks for opening the issue. 
It would be nice if you could provide some references or at least a draft for what you are suggesting.



> Additionally, the routine measures crosstalk at the bias point defined at the runcard (typically the sweetspot and therefore the least sensitive).

We could add an option for this. 

> For more accurate results, the routine should measure crosstalk at a highly sensitive point. A highly sensitive point can be obtained from the fit of the qubit flux dependence.

This depends on whether we are dealing with symmetric or asymmetric junctions, in the second case the definition of a flux insensitive point is not trivial. Do you know if the qubits that we are using are with symmetric or asymmetric junctions?
