### ISSUE TITLE
Randomized benchmarking and gate-set shadow estimation

### ISSUE THREAD

**Issue by scarrazza** [qiboteam/qibocal#85]
Roadmap from @ingoroth:

- [x] port existing qiborb functionality to qibocal to restore standard (single qubit Clifford) RB implementation https://github.com/qiboteam/qcvv/pull/92
- [x] Make scheme executable on quantum hardware
- [ ] Implement error bars
  - [ ] for standard RB
  - [ ] for filtered RB  
- [x]  implement ‘filtered' randomized benchmarking for non-self-inverting sequences (single qubit Clifford group)
- [ ]  implement (higher-order) simultaneous RB via filtering for all irreps (novel publishable scheme)
  - [ ]  (graphical plot/report for (higher-order) simultaneous RB)
- [ ]  random Gate classes for other groups {1, X}, ... ,  Heisenberg-Weyl, Dihedral
- [ ]  non-uniform generator RB (random gate classes that draw from generators) 
  - [ ]  (spectral gap computing tools for determining minimal required length for non-uniform RB) 
- [ ]  multi-qubit Clifford RB
- [ ]  universal random-circuit RB (XEB and so on)
- [ ]  cross-talk tomography (novel publishable scheme)
  - [ ]  (single exponential decay fitting for hetero-skedastic data + error bars (e.g. weighted linear least-squares) + statistical tests)

**Comment by wilkensJ** [comment]
First rb data from 5 qubit chip, run on qubit 2.
![qpu5q_standardrb](https://user-images.githubusercontent.com/70592365/198942712-425e5858-b4d2-4c7d-91cf-1e7d362b6a31.png)

**Comment by andrea-pasquale** [comment]
I believe that this issue is outdated given that there is #411.
Shall we close it?

**Comment by wilkensJ** [comment]
Yes thank you @andrea-pasquale.
