### ISSUE TITLE
Rabi length signal fit no longer works

### ISSUE THREAD

**Issue by andrea-pasquale** [qiboteam/qibocal#879]
While debugging the emulator I noticed that the fit for rabi length doesn't work anymore.
The bug was added by #857, the initial guess now for all rabi experiments is

https://github.com/qiboteam/qibocal/blob/a67eeaddf0d98ee35633d6e0be2232d05a0e382f/src/qibocal/protocols/rabi/utils.py#L294-L295

while before when running rabi length signal it was 
https://github.com/qiboteam/qibocal/blob/37d060599c739b3b70602505d29509af295aedb0/src/qibocal/protocols/rabi/length_signal.py#L171-L172

I believe that the -1 on the second term is triggering the error. Probably we will need to investigate more, for the being it would be enough if we are able to revert some of changes to the previous version of the code.
Here are the reports for [main](http://login.qrccluster.com:9000/YTs6fM2yTK-5lnx_A1tkxQ==/) and [before #857](http://login.qrccluster.com:9000/FL1XMvYrSS-8SVtjQkEUXQ==/) 
Could you take care of it @rodolfocarobene?

**Comment by rodolfocarobene** [comment]
I will work on this, have you understood why the limits where different?
