### ISSUE TITLE
T1 with probs fit not working

### ISSUE THREAD

**Issue by DavidSarlle** [qiboteam/qibocal#881]
T1 with probs fit not working, but the fit works with T1 signal

![image](https://github.com/qiboteam/qibocal/assets/39095664/5c0cf484-4023-4912-81ae-0a0f3d885a89)

**Comment by andrea-pasquale** [comment]
Thanks @DavidSarlle, could you provide a report with the data?

**Comment by DavidSarlle** [comment]
Sure! Here it is:

http://login.qrccluster.com:9000/8WwoQPB2T3-7av7aWC0SRA==
