### ISSUE TITLE
Advanced example broken in documentation

### ISSUE THREAD

**Issue by rodolfocarobene** [qiboteam/qibocal#901]
I'm talking about this example: https://qibo.science/qibocal/latest/tutorials/advanced.html

The code is a bit old and it doesn't work, for example the "Operation" does not exist anymore / has been moved somewhere else. We are planning to write a script to have T1 and T2 executed continuously over several hours, so I can take care of fixing this if it's ok for you :-)

**Comment by andrea-pasquale** [comment]
You are totally right! Thanks for spotting it.
That part of the documentation is outdated. There are "new" ways to run experiments in a python script.
See for example #865 and #870. Depending on when you are planning to have the experiment ready we can have a chat offline :)
