### ISSUE TITLE
Refactor plotting methods

### ISSUE THREAD

**Issue by andrea-pasquale** [qiboteam/qibocal#94]
Now in qibocal (`add_routines` branch), all the plotting methods are saved in scatters.py and heatmaps.py. These file are becoming quite long. It could be useful to re-organize them, as noted my @maxhant  in #78.
Given that we almost have  1:1 correspondence between calibration routines and plotting methods:

- frequency_msr_phase__fast_precision:
     - resonator_spectroscopy
     - qubit_spectroscopy
- frequency_flux_msr_phase:
      - resonator_spectroscopy_flux
      - qubit_spectroscopy_flux
- frequency_attenuation_msr_phase:
    - resonator_punchout
- frequency_attenuation_msr_phase__cut
    - resonator_punchout
- frequency_flux_msr_phase__matrix
    - resonator_spectroscopy_flux_matrix
- time_msr
    - ramsey_frequency_detuned
    - ramsey
-  t1_time_msr_phase
    -  t1
- time_msr_phase
    - rabi_pulse_length
-  gain_msr_phase
    -  rabi_pulse_gain
-   amplitude_msr_phase
    - rabi_pulse_amplitude
-  duration_gain_msr_phase
    - rabi_pulse_length_and_gain
- duration_amplitude_msr_phase
    - rabi_pulse_length_and_amplitude
- flips_msr_phase
    - flipping
- exc_gnd
    - calibrate_qubit_states_binning 
- prob_gate
   - allXY 
- prob_gate_iteration
    - allXY_iteration
- msr_beta
    - drag_pulse_tunning

A possible solution is to have a structure similar to what we have for the calibration routines.
```
plots/
* spectroscopy.py (with all the plots that referred to the resonator and the qubit spectroscopy)
* ramsey.py (with all the plots regarding ramsey)
* rabis.py (with all the plots regarding rabi oscillations)
```
and so on.
For some of the plotting methods we can also try to simplify the code where it is possible.
I don't think that this is a priority right now, since in `add_routines` all the plots are already working.
However, at some point we should see if we an simplify this structure.

**Comment by andrea-pasquale** [comment]
This is the issue that @maxhant was talking about @DavidSarlle @aorgazf.

**Comment by andrea-pasquale** [comment]
Fixed in #122

**Comment by maxhant** [comment]
Hi @andrea-pasquale, 
To be consistent, what do you think about doing the same for the fitting?

**Comment by andrea-pasquale** [comment]
Hi @maxhant,

the fitting files are way shorter compared to the plotting ones so for now I don't think that there is the need to split them into multiple files.

Cheers,
Andrea
