### ISSUE TITLE
`close` method of executor does not dump updated platform

### ISSUE THREAD

**Issue by andrea-pasquale** [qiboteam/qibocal#969]
`Executor.close()` is not dumping the platform.
It seems that we just need to pass `platform` to the new `Output` class created during the `close` method:
https://github.com/qiboteam/qibocal/blob/b1079b1d285afbd28313496075fd928e5e64242a/src/qibocal/auto/execute.py#L293

@alecandido feel free to implement this directly in #949 if you wish

**Comment by alecandido** [comment]
I should have added a test, to check this is working.

However, I'm not enthusiastic of these dumps, and they will be reviewed anyhow with #910. So, the fix has been added in #949, and I'm going to merge.
